name: kt-dynamodb
services:
  dynamodb:
    image: amazon/dynamodb-local:2.5.2
    ports:
      - "8000:8000"
  dynamodb-init:
      image: amazon/aws-cli:latest
      environment:
        AWS_ACCESS_KEY_ID: local
        AWS_SECRET_ACCESS_KEY: local
        AWS_ENDPOINT_URL: http://dynamodb:8000
        AWS_REGION: local-kt
      command:
        - dynamodb
        - create-table
        - --table-name
        - kt_local
        - --attribute-definitions
        - AttributeName=k,AttributeType=S
        - --key-schema
        - AttributeName=k,KeyType=HASH
        - --billing-mode
        - PAY_PER_REQUEST
      restart: on-failure

