name: 'kt-dynamodb'
services:
  'generate-keys':
    build:
      context: '..'
      dockerfile: './docker/Dockerfile'
      target: 'generate-keys'
    network_mode: 'none'
  'dynamodb':
    restart: 'on-failure'
    image: amazon/dynamodb-local:2.5.2
  'server':
    restart: 'on-failure'
    links:
      - 'dynamodb'
    build:
      context: ".."
      dockerfile: "./docker/Dockerfile"
      target: "run-server"
    command: [ "-config", "/run/secrets/config.yaml" ]
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_ENDPOINT_URL=http://dynamodb:8000
      - AWS_REGION=local-kt
    ports:
      - "8080:8080"
      - "8081:8081"
    secrets:
      - source: 'config'
        target: '/run/secrets/'
  'client':
    profiles:
      - 'client'
    depends_on:
      - 'server'
    build:
      context: ".."
      dockerfile: "./docker/Dockerfile"
      target: "run-client"
    entrypoint: [ "sh" ]
    secrets:
      - source: 'config'
        target: '/run/secrets/'
    network_mode: 'host'
secrets:
  'config':
    file: '../example/'
