kt:
  server-addr: test-server:8082
  authorized-headers:
    ExampleHeader1:
      - example value one
      - example value two
  header-value-to-auditor-name:
    example value one: example-auditor-1
    example value two: example-auditor-2

kt-query:
  server-addr: test-server:8080

kt-test:
  server-addr: test-server:8081

metrics-addr: test-server:8083
health-addr: test-server:8084

# Paste in the keys generated via `docker compose run --rm generate-keys`
api:
  signing-key: abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcd
  vrf-key: abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcd
  prefix-key: abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcd
  opening-key: abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcd
  # fake:
  #   count: 1
  #   interval: 10s
  distinguished: 1m
  auditors:
    example-auditor-1: abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcd
    example-auditor-2: abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcdef1234abcd
  min-search-delay: 1s
  min-monitor-delay: 1s
  jitter-percent: 10

# DynamoDB
db:
  table: kt_local
  parallel: 2

account-db: mock
